spring.application.name=ChatOnline

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Tự động tạo/cập nhật bảng dựa trên các Entity Java của bạn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#secretKey
app.auth.tokenSecret=${TOKEN_SECRET}

# Cấu hình kết nối Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#SSL
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:chatonline.p12
server.ssl.key-store-password=${PASSWORD_SSL}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=chatonline 
#private key va certificate nam trong entry chatonline kieu PrivateKeyEntry cua keystore



#keytool -list -v -keystore chatonline.p12
