spring.application.name=ChatOnline

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

# Tự động tạo/cập nhật bảng dựa trên các Entity Java của bạn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#secretKey
app.auth.tokenSecret=${TOKEN_SECRET}
